# mysql-db-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
spec:
  replicas: 1 # Typically only one replica for a database
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          # change to mysql container image
          image: mysql:5.7
          ports:
            - containerPort: 3306 # Adjust the port as needed
          # separate secrets file that holds the pw
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
