# video-streaming-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-streaming
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: pippenpat/video_stream:latest
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: mysql-db-service
            - name: FILE_STORAGE_URL
              value: file-system-service
          # Add other environment variables as needed
          volumeMounts:
            - mountPath: /app/stored_files
              name: uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming-service
spec:
  selector:
    app: video-streaming
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
