apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Darren\Downloads\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-service
  name: auth_service
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: auth-service
status:
  loadBalancer: {}
