apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Darren\Downloads\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: file-system-service
  name: file_system_service
spec:
  ports:
    - name: "3004"
      port: 3004
      targetPort: 3000
  selector:
    io.kompose.service: file-system-service
status:
  loadBalancer: {}
