apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Darren\Downloads\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-db
  name: mysql_db
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    io.kompose.service: mysql-db
status:
  loadBalancer: {}
