apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Darren\Downloads\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: upload-video-app
  name: upload_video_app
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3000
  selector:
    io.kompose.service: upload-video-app
status:
  loadBalancer: {}
