apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Darren\Downloads\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: upload-video-app
  name: upload-video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: upload-video-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Darren\Downloads\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: upload-video-app
    spec:
      containers:
        - image: upload-video-app
          name: upload_video_app
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app/uploads
              name: uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
status: {}
